### ISSUE TITLE
Generator.generate_swagger is not working if destination path is not provided

### ISSUE THREAD

**Issue by fizaashraf37** [coding-kitties/flask-swagger-generator#22]
Destination path parameter in generate_swagger function of Generator class is optional. It works when the parameter is passed. But when destination path is not provided then it throws below error:

```
Traceback (most recent call last):
  File "e:/OpenSource/flask-swagger-generator/test.py", line 28, in <module>
    generator.generate_swagger(app)
  File "e:\OpenSource\flask-swagger-generator\flask_swagger_generator\generators\generator.py", line 53, in generate_swagger
    self.file = open(destination_path, 'w')
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Example:**

`generator.generate_swagger(app)`

**Comment by fizaashraf37** [comment]
I have also found the solution. And have created the below PR for the fix.
https://github.com/coding-kitties/flask-swagger-generator/pull/23
