### ISSUE TITLE
No support for Nested Schema for request/responses

### ISSUE THREAD

**Issue by fizaashraf37** [coding-kitties/flask-swagger-generator#28]
If user passes a json schema for request or response with nested fields as in this example:

```
@generator.request_body({'id': 10, 'name': 'test_object', "values": {"id":1, "name":"test"}})
@blueprint.route('/objects/<int:object_id>', methods=['PUT'])
def update_object(object_id):
    return jsonify({'id': 1, 'name': 'test_object_name'}), 201
```

It generates below error:

```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    @blueprint.route('/objects/<int:object_id>', methods=['PUT'])
  File "E:\OpenSource\flask-swagger-generator\flask_swagger_generator\generators\generator.py", line 83, in swagger_request_body
    func.__name__, schema
  File "E:\OpenSource\flask-swagger-generator\flask_swagger_generator\specifiers\swagger_three_specifier.py", line 660, in add_request_body   
    schema
  File "E:\OpenSource\flask-swagger-generator\flask_swagger_generator\specifiers\swagger_three_specifier.py", line 70, in __init__
    self.get_type(schema[key]).value
AttributeError: 'NoneType' object has no attribute 'value'
```

This prevents nested object to get added in schema and also generates invalid yaml.

**Comment by fizaashraf37** [comment]
I have created a feature branch for this and have also created [PR#29](https://github.com/coding-kitties/flask-swagger-generator/pull/29)

**Comment by MDUYN** [comment]
Lets keep this issue open and update it when its resolved
